dependencies {
    modImplementation(project(":modules:CTNH-Lib")){transitive = false}
    modImplementation(project(":modules:Create-Enough-Items")){ transitive = false }


    modImplementation(ctnh.geckolib)
    modImplementation(ctnh.placebo)
    modImplementation(ctnh.ali)
    modImplementation(ctnh.hostile)

    modImplementation(ctnh.biomancy)
    modImplementation(ctnh.biofactory)

    modLocalRuntime(ctnh.constructionwand)
    modLocalRuntime(ctnh.citadel)

}
